# Lifeboard Ecosystem Docker Compose Example Template
# Rename or copy to compose.yaml

name: lifeboard-ecosystem

services:
  lifeboard-legacy:
    build:
      context: ./lifeboard-legacy
    ports:
      - "8080:80"
    restart: unless-stopped

  gtodo-be-net:
    build:
      context: ./glorified-todo/gtodo-be-net
      dockerfile: gtodo-be-net.Application/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped

  gtodo-fe-angular:
    build:
      context: ./glorified-todo/gtodo-fe-angular
    ports:
      - "4200:80"
    restart: unless-stopped

  finances-fe-angular:
    build:
      context: ./Finances/finances-fe-angular
    ports:
      - "4201:80"
    restart: unless-stopped

  housesheet-fe-angular:
    build:
      context: ./housesheet/housesheet-fe-angular
    ports:
      - "4202:80"
    restart: unless-stopped

  storeroom-fe-angular:
    build:
      context: ./storeroom/storeroom-fe-angular
    ports:
      - "4203:80"
    restart: unless-stopped
